parserOptions:
  ecmaVersion: 8

rules:
  indent: ['error', 4]
  brace-style: ['error', 'stroustrup']
  func-style: ['error', 'declaration', { allowArrowFunctions: true }]
  strict: ['error', 'global']
  space-before-function-paren: ['error', { anonymous: 'always', named: 'never', asyncArrow: 'always' }]
  space-before-blocks: ['error', 'always']
  keyword-spacing: ['error', { before: true, after: true }]
  array-bracket-spacing: ['error', 'never']
  arrow-spacing: ['error', { before: true, after: true }]
  comma-spacing: ['error', { before: false, after: true }]
  object-curly-spacing: ['error', 'always']
  space-infix-ops: 'error'
  space-in-parens: ['error', 'never']
